Repository guardian/gateway, pull requests merged in 2020-10, with the labels that each got.

#40 Login Checking for data flow
  .env.example
  ci.env
  cloudformation.yaml
  src/server/lib/__tests__/configuration.test.ts
  src/server/lib/configuration.ts
  src/server/lib/idapi/auth.ts
  src/server/lib/middleware/login.ts
  src/server/models/Configuration.ts
  src/server/routes/consents.ts
  src/shared/model/IDAPIAuth.ts
Labels: enhancement

#41 Consents | Email verification error handling
  ci.env
  src/client/components/GlobalState.tsx
  src/client/lib/fonts.ts
  src/client/pages/ConsentsData.tsx
  src/client/pages/ConsentsNewsletters.tsx
  src/client/pages/ResendEmailVerification.tsx
  src/client/pages/ResetSent.tsx
  src/client/routes.tsx
  src/server/lib/baseUri.ts
  src/server/lib/clientId.ts
  src/server/lib/idapi/auth.ts
  src/server/lib/idapi/consents.ts
  src/server/lib/idapi/newsletters.ts
  src/server/lib/idapi/user.ts
  src/server/lib/idapi/verifyEmail.ts
  src/server/lib/middleware/helmet.ts
  src/server/lib/middleware/login.ts
  src/server/lib/playSessionCookie.ts
  src/server/lib/returnUrl.ts
  src/server/lib/setIDAPICookies.ts
  src/server/routes/consents.ts
  src/server/routes/index.ts
  src/server/routes/verifyEmail.ts
  src/shared/lib/emailProvider.ts
  src/shared/model/Errors.ts
  src/shared/model/GlobalState.ts
  src/shared/model/Routes.ts
  src/shared/model/User.ts
  start-dev.sh
Labels: enhancement

#54 Marketing consents to use checkboxes.
  src/client/layouts/ConsentsLayout.tsx
  src/client/pages/ConsentsCommunication.tsx
  src/client/pages/ConsentsData.tsx
Labels: enhancement

#63 Dependencies Update - October 2020
  .github/dependabot.yml
  package.json
  src/client/pages/ChangePasswordComplete.tsx
  src/shared/model/QueryParams.ts
  yarn.lock
Labels: dependencies

#76 Update dependabot to be weekly to stop spam
  .github/dependabot.yml
Labels: hacktoberfest-accepted

#78 Cloudformation | Set max instance count to 12
  cloudformation.yaml
Labels: hacktoberfest-accepted
