Repository guardian/gateway, pull requests merged in 2022-03, with the labels that each got.

#1549 Show loading spinner when the form is disabled upon submit
  src/client/components/MainForm.tsx
Labels: enhancement

#1492 Rate Limiting (pt. 1): Implement redis backed token bucket rate limiter
  .env.example
  .github/workflows/cypress-ete-okta.yml
  .github/workflows/cypress-ete.yml
  .github/workflows/cypress-mocked.yml
  .gitignore
  cloudformation.yaml
  cypress-mocked.env
  package.json
  src/server/lib/__tests__/getConfiguration.test.ts
  src/server/lib/__tests__/rate-limit/rateLimit.test.ts
  src/server/lib/crypto.ts
  src/server/lib/getConfiguration.ts
  src/server/lib/rate-limit/bucket.ts
  src/server/lib/rate-limit/index.ts
  src/server/lib/rate-limit/keys.ts
  src/server/lib/rate-limit/rateLimit.ts
  src/server/lib/rate-limit/types.ts
  src/server/models/Configuration.ts
  yarn.lock
Labels: enhancement

#1572 March 16th 2022 | Dependency Updates
  package.json
  src/server/routes/signIn.ts
  yarn.lock
Labels: dependencies

#1577 Add and update Okta inline code documentation
  src/server/lib/__tests__/okta/api/users.test.ts
  src/server/lib/__tests__/okta/register.test.ts
  src/server/lib/okta/api/authentication.ts
  src/server/lib/okta/api/errors.ts
  src/server/lib/okta/api/headers.ts
  src/server/lib/okta/api/responses.ts
  src/server/lib/okta/api/users.ts
  src/server/lib/okta/oauth.ts
  src/server/lib/okta/openid-connect.ts
  src/server/lib/okta/register.ts
  src/server/lib/okta/validateEmail.ts
  src/server/models/okta/User.ts
Labels: documentation

#1600 Upgrade dependencies to latest versions where possible (28th March 2022)
  package.json
  src/server/lib/__tests__/rate-limit/rateLimit.test.ts
  yarn.lock
Labels: dependencies
