Repository guardian/gateway, pull requests merged in 2022-02, with the labels that each got.

#1453 February 7th 2022 | Dependency Updates
  package.json
  yarn.lock
Labels: dependencies

#1487 Dependency upgrade 15th Feb
  .storybook/main.js
  package.json
  yarn.lock
Labels: dependencies

#1491 Fix email input validation for Samsung Internet
  src/client/components/EmailInput.tsx
Labels: bug

#1506 Add disableOnSubmit prop to MainForm
  cypress/integration/ete/reset_password/reset_password.spec.ts
  cypress/integration/mocked/change_password.spec.ts
  src/client/__tests__/MainForm.test.tsx
  src/client/components/MainForm.tsx
  src/client/components/PasswordForm.tsx
  src/client/layouts/Main.tsx
Labels: enhancement
