Repository guardian/gateway, pull requests merged in 2023-10, with the labels that each got.

#2423 Dependencies | October 2nd 2023
  makefile
  package.json
  src/email/lib/send.ts
  src/server/lib/awsConfig.ts
  yarn.lock
Labels: dependencies, hacktoberfest-accepted

#2424 Okta OIE Prep | Update Sign In Page Interception Code
  scripts/okta/__tests__/getClientId.test.ts
  scripts/okta/__tests__/getRedirectUrl.test.ts
  scripts/okta/__tests__/getThirdPartyClientId.test.ts
  scripts/okta/__tests__/getThirdPartyReturnUrl.test.ts
  scripts/okta/lib/helper.ts
  scripts/okta/okta-login.js
Labels: hacktoberfest-accepted

#2427 OAuth | Correctly assert `clientId` when verifying tokens
  src/server/lib/okta/tokens.ts
Labels: hacktoberfest-accepted

#2428 Dependencies | October 9th 2023
  package.json
  yarn.lock
Labels: dependencies, hacktoberfest-accepted

#2444 Handle maxAge parameter
  scripts/okta/__tests__/getMaxAge.test.ts
  scripts/okta/__tests__/getRedirectUrl.test.ts
  scripts/okta/lib/helper.ts
  scripts/okta/okta-login.js
  src/server/lib/middleware/redirectIfLoggedIn.ts
  src/server/lib/queryParams.ts
  src/shared/model/QueryParams.ts
Labels: hacktoberfest-accepted

#2452 Dependencies | October 23rd 2023
  package.json
  yarn.lock
Labels: dependencies

#2451 Okta | Remove "fallback" option for apps
  docs/okta/native-apps-integration-guide.md
  scripts/okta/__tests__/getRedirectUrl.test.ts
  scripts/okta/lib/helper.ts
  scripts/okta/okta-login.js
  src/client/.well-known/apple-app-site-association
  src/server/routes/oauth.ts
Labels: hacktoberfest-accepted

#2456 Dependencies | October 30th 2023
  package.json
  yarn.lock
Labels: dependencies
